apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-service
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - image: book-service
        name: book-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
          - containerPort: 9001
        env:
          - name: BLP_JVM_THREAD_COUNT
            value: "50"
          - name: SPRING_DATASOURCE_USERNAME
            value: user
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://book-postgres/book-db
